import type { Metadata, Viewport } from "next";
import { Geist, Geist_Mono, Inter, Instrument_Serif, Shadows_Into_Light, Lobster_Two } from "next/font/google";
// @ts-ignore
import "./globals.css";
import { CartProvider } from "./context/cartContext";
import { LanguageProvider } from "./context/LanguageContext";
import LanguageToggle from "./components/LanguageToggle";



const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

const lobster = Lobster_Two({
  subsets: ["latin"],
  weight: ["400"],
  variable: "--font-lobster",
  display: "swap",
})


const instrument = Instrument_Serif({
  weight: '400',
  variable: '--font-instrument-serif', // Optional: for use with CSS variables or Tailwind CSS
  subsets: ['latin'],
  display: 'swap', // Optional: 'swap' ensures text is visible while the font is loading
});

const shadows = Shadows_Into_Light({
  weight: '400',
  variable: '--font-shadow-serif', // Optional: for use with CSS variables or Tailwind CSS
  subsets: ['latin'],
  display: 'swap', // Optional: 'swap' ensures text is visible while the font is loading


})


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Andy's Bakery",
  description: "Generated by create next app",
};

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
  viewportFit: "cover",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" >
      <body
        className={`${instrument.variable} ${lobster.variable} ${shadows.variable}  antialiased`}>
        <LanguageProvider>
          <CartProvider>
              <LanguageToggle className="siteLanguageToggle" />
              {children}
          </CartProvider>
        </LanguageProvider>


      </body>
    </html>
  );
}
